server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: demo
    password: demo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# SM2 演示密钥对（生产请外置轮换）
jwt:
  private-key-hex: "00bf1f725980254bc636b6a9944e3f18e74f8f035a2beb1507bfad05713689bb4d"
  public-key-hex: "049c83f48a0962c7f977503cdd64b042513c64a969070e49df9073b29eacf7c90fe2729afc27adc4575c00973eaf7228cdf14ee47215f11a8af25cebf2cc352c73"
  expire-ms: 7200000
  renew-threshold-ms: 1800000

captcha:
  ttl-seconds: 300
  width: 130
  height: 48
  code-count: 4
